#!/bin/sh

echo "Is it morning? Please answer yes or no"
read timeofday
while [ "$timeofday" = "" ]
do
    read timeofday
done
case "$timeofday" in
    [Yy] | [Yy][Ee][Ss] ) echo "Good Morning";;
    n*  | N* )            echo "Good Afternoon";;
    * )                   echo "Sorry, answer not recognised";;
esac

exit 0