#!/bin/sh

echo "Is it morning? Please answer yes or no"
read timeofday
while [ "$timeofday" = "" ]
do
       read timeofday
done
case "$timeofday" in
[Yy] | [Yy][Ee][Ss])
       echo "Good Morning"
       echo "Up bright and early this morning?"
       ;;
[nN] | [Nn][Oo])
       echo "Good Afternoon"
       ;;
* )
       echo "Sorry, answer not recognised"
       echo "Please answer yes or no"
       exit 1
       ;;
esac

exit 0